### PR TITLE
Fix value restoration in n2tvp_r

### LINKED ISSUE #12: Segfault after lua_yield()
LuaVela as a drop-in replacement crashes in our environment where Lua threads are used extensively. Please see the following code snippet that illustrates the problem:
```c
#include <lauxlib.h>
#include <lualib.h>

static int yield(lua_State *L) {
    return lua_yield(L, lua_gettop(L));
}

int main(void) {
    lua_State *L = luaL_newstate();
    lua_State *T = lua_newthread(L);
    lua_pushcfunction(L, yield);
    lua_setglobal(L, "yield");
    luaL_openlibs(L);
    luaL_loadstring(T, "print('ENTER #1');yield();print('LEAVE #1')");
    lua_resume(T, 0); /* ENTER #1 */
    lua_resume(T, 0); /* LEAVE #1 */
    /* Normally finished thread can be reused - https://www.lua.org/manual/5.3/manual.html#lua_status */
    luaL_loadstring(T, "print('ENTER #2');yield();print('LEAVE #2')");
    lua_resume(T, 0); /* ENTER #2 */
    lua_resume(T, 0); /* LEAVE #2 */
    lua_close(L);
    return 0;
}
```
Expected output:
```
ENTER #1
LEAVE #1
ENTER #2
LEAVE #2
```
Observed output:
```
ENTER #1
Segmentation fault (core dumped)
```
Output under gdb:
```
...
(gdb) r
Starting program: /mnt/seny/devel/tmp/a.out
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
ENTER #1

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7e71a79 in lj_BC_RET () from /home/seny/local/lib/libujit.so.0
(gdb) bt
#0  0x00007ffff7e71a79 in lj_BC_RET () from /home/seny/local/lib/libujit.so.0
#1  0x00007ffff7e9f91b in lua_resume (L=0x7ffff7acb338, nargs=0) at /home/seny/devel/luavela/src/uj_capi.c:1037
#2  0x0000555555555274 in main () at ujit1.c:15
```

### PR DESCRIPTION
**Pull request by igelhaus**
This patch fixes the behavior of `n2tvp_r` macro in the VM core. This macro is used to calculate the effective address of `TValue`s on Lua stack using the stack base and x2-encoded `narg` offset. After the effective address is calculated, the offset is restored to its original value.

Normally the offset is a non-negative number, with a single exception: when the `return lua_yield(...);` idiom is used for a C function, -1 will be returned to the interpreter. Without this patch, this value was handled incorrectly by `n2tvp_r`.

Fixes #12.

### CODE REVIEW

File: tests/impl/uJIT-tests-C/suite/test_lua_yield.c [hunk 1]
```diff
@@ -0,0 +1,85 @@
...
+
+static void assert_yielded(lua_State *L, const char *status)
+{
+	assert_int_equal(lua_status(L), LUA_YIELD);
+	assert_stack_size(L, 1);
+	test_string(L, -1, status);
+	lua_pop(L, 1);
+}
+
+static void assert_global(lua_State *L, const char *name, const char *value)
```
Comment (igormunkin) [inline tests/impl/uJIT-tests-C/suite/test_lua_yield.c]: Minor: I guess this one can be moved to `test_common_lua.h`, since it looks like a generic check. Feel free to ignore :)

**Comment by igormunkin** [comment]
@igelhaus, the patch is neat, thanks! LGTM.

File: tests/impl/uJIT-tests-C/suite/test_lua_yield.c (hunk 1 above)
Comment (igelhaus) [reply tests/impl/uJIT-tests-C/suite/test_lua_yield.c]: Good point, fixed. Thanks!
